import "../styles/globals.css";
import Head from "next/head";
import UserContext from "../src/components/context/userContext";
import { useContext, useEffect, useState } from "react";
import Database from "../src/components/Database.js";

export default function App({ Component, pageProps }) {
  const [handlerDatabase, setHandlerDatabase] = useState(Database);
  const [checkReg, setCheckReg] = useState("hidden");
  const [serip, setSerip] = useState(0);
  const [name, setNamep] = useState("");
  const [numberIdProduct, setNumberIdProduct] = useState(0);
  const [flag, setFlag] = useState([]);
  const [cookie, setCookie] = useState(pageProps.token);

  return (
    <>
      <UserContext.Provider
        value={{
          handlerDatabase,
          setHandlerDatabase,
          checkReg,
          setCheckReg,
          serip,
          setSerip,
          numberIdProduct,
          setNumberIdProduct,
          name,
          setNamep,
          flag,
          setFlag,
          cookie,
          setCookie,
        }}
      >
        <Head>
          <title>Smart Torob</title>
          <meta name="description" content="Generated by Rahimtech" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </UserContext.Provider>
    </>
  );
}
export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}
