import "../styles/globals.css";
import Head from "next/head";
import UserContext from "../src/components/context/userContext";
import { useState } from "react";
import Database from "../src/components/Database.js";
import { SessionProvider } from "next-auth/react";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  const [handlerDatabase, setHandlerDatabase] = useState(Database);
  const [checkReg, setCheckReg] = useState("hidden");
  const [serip, setSerip] = useState(0);
  const [name, setNamep] = useState("");
  const [numberIdProduct, setNumberIdProduct] = useState(0);
  const [flag, setFlag] = useState([]);

  return (
    <>
      <UserContext.Provider
        value={{
          handlerDatabase,
          setHandlerDatabase,
          checkReg,
          setCheckReg,
          serip,
          setSerip,
          numberIdProduct,
          setNumberIdProduct,
          name,
          setNamep,
          flag,
          setFlag,
        }}
      >
        <Head>
          <title>Smart Torob</title>
          <meta name="description" content="Generated by Rahimtech" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <SessionProvider session={session}>
          <Component {...pageProps} />
        </SessionProvider>
      </UserContext.Provider>
    </>
  );
}
